server:
  port: 8800
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 写 xml 必配
  mapper-locations: classpath*:xyz/funnyboy/*/mapper/xml/*Mapper.xml
spring:
  # 数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  # JSON
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password: 123456
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  activiti:
    #   false: 默认，数据库表不变，但是如果版本不对或者缺失表会抛出异常（生产使用）
    #   true: 表不存在，自动创建（开发使用）
    #   create_drop: 启动时创建，关闭时删除表（测试使用）
    #   drop_create: 启动时删除表,在创建表 （不需要手动关闭引擎）
    database-schema-update: true
    #   监测历史表是否存在，activities7 默认不开启历史表
    db-history-used: true
    #   none：不保存任何历史数据，流程中这是最高效的
    #   activity：只保存流程实例和流程行为
    #   audit：除了 activity，还保存全部的流程任务以及其属性，audit 为 history 默认值
    #   full：除了 audit、还保存其他全部流程相关的细节数据，包括一些流程参数
    history-level: full
    #   校验流程文件，默认校验 resources 下的 process 文件夹的流程文件
    check-process-definitions: true
wechat:
  mpAppId: wx7d5d9fae8a9832b9
  mpAppSecret: 1a5e23288e3dce0779a9b5dc9c420604
  # 前端接口
  frontUrl: http://funnyboy.nat300.top
  # 授权回调获取用户信息接口地址
  backUrl: http://funnymudpee.natapp1.cc/admin/wechat/userInfo
